
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eetna
 */
public class AutobattleGUI extends javax.swing.JFrame {

    Jatekos j;
    Thread t;
    String ellenfelek[]={"Khanjali","APC","Rhina","Apocalyps","Scarab","Chernobog"};
    String ellenfel;
    
    public AutobattleGUI() {
        initComponents();
    }
    public AutobattleGUI(Jatekos k) throws MalformedURLException, CloneNotSupportedException{
        this.j=(Jatekos) k.clone();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/kepek/ikon.png")).getImage());
        jTextField18.setText(Integer.toString(j.getElet()));
        jTextField19.setText(Integer.toString(j.getPajzs()));
        jTextField20.setText(Integer.toString(j.getFegyver()));
        if (this.j.getKikerul()){
            jButton4.setEnabled(false);
        }
        int r=(int)(Math.random()*ellenfelek.length);
        ellenfel=ellenfelek[r];
        jLabel5.setText(j.getNev()+" (Te)");
        jLabel6.setText(ellenfel);
        jLabel1.setIcon(new ImageIcon(new URL(j.getKarakter()+"/b.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setMinimumSize(new java.awt.Dimension(862, 835));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("");
        jLabel1.setName("player"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 650, 110, 110);

        jButton1.setBackground(new java.awt.Color(36, 41, 44));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jButton1.setText("Harcra fel!");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 41, 44)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(95, 95));
        jButton1.setMinimumSize(new java.awt.Dimension(95, 95));
        jButton1.setName("hpbutton"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(95, 95));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(385, 340, 95, 95);

        jButton2.setBackground(new java.awt.Color(36, 41, 44));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 41, 44)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton2.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(jButton2);
        jButton2.setBounds(185, 395, 70, 70);

        jButton3.setBackground(new java.awt.Color(36, 41, 44));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 41, 44)));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jButton3.setFocusable(false);
        jButton3.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton3.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton3.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 395, 70, 70);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(395, 70, 78, 125);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-Shield-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 470, 120, 13);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-MOD-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 470, 130, 13);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(36, 41, 44));
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        jTextField1.setFocusable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 10, 5, 76);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(72, 82, 88));
        jTextField2.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Élet:");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.setFocusable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(85, 30, 70, 15);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(72, 82, 88));
        jTextField3.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Pajzs:");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.setFocusable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(85, 45, 70, 15);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(72, 82, 88));
        jTextField4.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Fegyver");
        jTextField4.setToolTipText("");
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField4.setFocusable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(85, 60, 70, 15);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(36, 41, 44));
        jTextField7.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField7.setText("1");
        jTextField7.setToolTipText("");
        jTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField7.setFocusable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(155, 30, 35, 15);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(36, 41, 44));
        jTextField8.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField8.setText("0");
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField8.setFocusable(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(155, 45, 35, 15);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(36, 41, 44));
        jTextField9.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField9.setText("1");
        jTextField9.setToolTipText("");
        jTextField9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField9.setFocusable(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(155, 60, 35, 15);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(36, 41, 44));
        jTextField12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        jTextField12.setFocusable(false);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(670, 710, 5, 76);

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(72, 82, 88));
        jTextField13.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("Élet:");
        jTextField13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField13.setFocusable(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(680, 725, 70, 15);

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(72, 82, 88));
        jTextField14.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("Pajzs:");
        jTextField14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField14.setFocusable(false);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(680, 740, 70, 15);

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(72, 82, 88));
        jTextField15.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("Fegyver");
        jTextField15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField15.setFocusable(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(680, 755, 70, 15);

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(36, 41, 44));
        jTextField18.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField18.setFocusable(false);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(750, 725, 35, 15);

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(36, 41, 44));
        jTextField19.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField19);
        jTextField19.setBounds(750, 740, 35, 15);

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(36, 41, 44));
        jTextField20.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField20.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jTextField20.setFocusable(false);
        getContentPane().add(jTextField20);
        jTextField20.setBounds(750, 755, 35, 15);

        jButton4.setText("Kitér");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 780, 55, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/Autobattle.jpg"))); // NOI18N
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 862, 835);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        if (evt.getKeyCode()==27){
            System.exit(0);}
    }//GEN-LAST:event_jLabel2KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode()==27){
            System.exit(0);}
    }//GEN-LAST:event_formKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       j.setKikerul(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int dobj=(int)(Math.random()*6+1);
        int dobg=(int)(Math.random()*6+1);
        jButton2.setText(Integer.toString(dobg));
        jButton3.setText(Integer.toString(dobj));
        jButton1.setEnabled(false);
        if (dobj>dobg){
           t= new Thread(new Runnable() {
           @Override
           public void run() {
            jButton1.setText("<html> "+j.getNev()+"<br> nyert </html>");try {
                Thread.sleep(5000);
                dispose();
               } catch (InterruptedException ex) {
                   Logger.getLogger(AutobattleGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
}});
            t.start();
        }
        else if (dobj==dobg){jButton1.setText("döntetlen");jButton1.setEnabled(true);}
        else{
            jButton1.setText("<html> "+ellenfel+"<br> nyert </html>");
            j.setVeszitFegyver();
            Frissit();
            if (j.getFegyver()<=0){
                j.setHelyzet(71); //töktő mező
               t= new Thread(new Runnable() {
           @Override
           public void run() {
               try {
                   Thread.sleep(5000);
               } catch (InterruptedException ex) {
                   Logger.getLogger(AutobattleGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
                dispose();}});
               t.start();
            }
            else{
                jButton1.setEnabled(true);
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutobattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutobattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutobattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutobattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutobattleGUI().setVisible(true);
            }
        });
    }
    
    public void Frissit(){
        jTextField18.setText(Integer.toString(j.getElet()));
        jTextField19.setText(Integer.toString(j.getPajzs()));
        jTextField20.setText(Integer.toString(j.getFegyver()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
