
import java.awt.Frame;
import java.awt.event.WindowListener;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eetna
 */
public class BattlemapGUI extends javax.swing.JFrame {

    Jatekos jatekosok[];
    JTextField kek[];
    JTextField piros [];
    int kmax, pmax;
    Thread t;
    Boolean zart=false;
    Boolean kfegy, pfegy; //ha igaz akkor a fegyverzetet szorozza, ellenben a védelmet
    Boolean kekjon,tamad; //igaz ha kék hamis ha piros
    public BattlemapGUI() {
        kek=new JTextField[5];
        piros=new JTextField[5];
        initComponents();
        Dobokockak();
    }
    public BattlemapGUI(Jatekos jatekosok[]) throws CloneNotSupportedException, MalformedURLException{
        this.jatekosok=jatekosok;
        this.jatekosok[0]=(Jatekos)jatekosok[0].clone();
        this.jatekosok[1]=(Jatekos)jatekosok[1].clone();
        kek=new JTextField[5];
        piros=new JTextField[5];
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/kepek/ikon.png")).getImage());
        Dobokockak();
        if (jatekosok[0].getKarakter().equals(getClass().getResource("kepek/kek1"))){
            this.kfegy=false;
        }
        else{this.kfegy=true;}
        if (jatekosok[1].getKarakter().equals(getClass().getResource("kepek/piros1"))){
            this.pfegy=true;
        }
        else{this.pfegy=false;}
        jLabel2.setIcon(new ImageIcon(new URL(jatekosok[0].getKarakter()+"/harc.png")));
        jLabel3.setIcon(new ImageIcon(new URL(jatekosok[1].getKarakter()+"/harc.png")));
        int r=(int)(Math.random()*2);
        if (r==0){kekjon=true;tamad=true;jLabel4.setText("Támad");jLabel5.setText("Védekezik");jButton1.setEnabled(false);}
        else{kekjon=false;tamad=false;jLabel5.setText("Támad");jLabel4.setText("Védekezik");jButton2.setEnabled(false);} // ki fog kezdeni
        Frissit();
        jTextField3.setText(jatekosok[0].getNev());
        jTextField2.setText(jatekosok[1].getNev());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        k1 = new javax.swing.JTextField();
        k4 = new javax.swing.JTextField();
        k3 = new javax.swing.JTextField();
        k5 = new javax.swing.JTextField();
        k2 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setMinimumSize(new java.awt.Dimension(1199, 1100));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setInheritsPopupMenu(false);
        jLabel2.setMaximumSize(new java.awt.Dimension(130, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(130, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 100));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 350, 130, 100);
        //jLabel2.setIcon(new ImageIcon(new URL(jatekosok[0].getKarakter()));

            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jLabel3.setFocusable(false);
            jLabel3.setMaximumSize(new java.awt.Dimension(130, 100));
            jLabel3.setMinimumSize(new java.awt.Dimension(130, 100));
            jLabel3.setPreferredSize(new java.awt.Dimension(130, 100));
            getContentPane().add(jLabel3);
            jLabel3.setBounds(1030, 350, 130, 100);

            jPanel2.setBackground(new java.awt.Color(0, 0, 102));
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 4));

            jTextField3.setEditable(false);
            jTextField3.setBackground(new java.awt.Color(36, 41, 44));
            jTextField3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
            jTextField3.setForeground(new java.awt.Color(255, 255, 255));
            jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            jTextField3.setText("Player  Blue");
            jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

            jTextField14.setEditable(false);
            jTextField14.setBackground(new java.awt.Color(36, 41, 44));
            jTextField14.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField14.setForeground(new java.awt.Color(255, 255, 255));
            jTextField14.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
            jTextField14.setText("Élet erő:");
            jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

            jTextField21.setEditable(false);
            jTextField21.setBackground(new java.awt.Color(36, 41, 44));
            jTextField21.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField21.setForeground(new java.awt.Color(255, 255, 255));
            jTextField21.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
            jTextField21.setText("Pajzs:");
            jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

            jTextField22.setEditable(false);
            jTextField22.setBackground(new java.awt.Color(36, 41, 44));
            jTextField22.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField22.setForeground(new java.awt.Color(255, 255, 255));
            jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField22.setText("6");
            jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

            jTextField23.setEditable(false);
            jTextField23.setBackground(new java.awt.Color(36, 41, 44));
            jTextField23.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField23.setForeground(new java.awt.Color(255, 255, 255));
            jTextField23.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
            jTextField23.setText("Fegyver:");
            jTextField23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

            jTextField24.setEditable(false);
            jTextField24.setBackground(new java.awt.Color(36, 41, 44));
            jTextField24.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField24.setForeground(new java.awt.Color(255, 255, 255));
            jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField24.setText("5");
            jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

            jTextField25.setEditable(false);
            jTextField25.setBackground(new java.awt.Color(36, 41, 44));
            jTextField25.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField25.setForeground(new java.awt.Color(255, 255, 255));
            jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField25.setText("5");
            jTextField25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField22))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField25))
                    .addGap(20, 20, 20))
            );

            getContentPane().add(jPanel2);
            jPanel2.setBounds(10, 10, 150, 130);

            jPanel1.setBackground(new java.awt.Color(102, 0, 0));
            jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 4));

            jTextField2.setEditable(false);
            jTextField2.setBackground(new java.awt.Color(36, 41, 44));
            jTextField2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
            jTextField2.setForeground(new java.awt.Color(255, 255, 255));
            jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            jTextField2.setText("Player Red");
            jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

            jTextField13.setEditable(false);
            jTextField13.setBackground(new java.awt.Color(36, 41, 44));
            jTextField13.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField13.setForeground(new java.awt.Color(255, 255, 255));
            jTextField13.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
            jTextField13.setText(":Élet erő");
            jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

            jTextField15.setEditable(false);
            jTextField15.setBackground(new java.awt.Color(36, 41, 44));
            jTextField15.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField15.setForeground(new java.awt.Color(255, 255, 255));
            jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField15.setText("7");
            jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

            jTextField19.setEditable(false);
            jTextField19.setBackground(new java.awt.Color(36, 41, 44));
            jTextField19.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField19.setForeground(new java.awt.Color(255, 255, 255));
            jTextField19.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
            jTextField19.setText(":Pajzs");
            jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

            jTextField18.setEditable(false);
            jTextField18.setBackground(new java.awt.Color(36, 41, 44));
            jTextField18.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField18.setForeground(new java.awt.Color(255, 255, 255));
            jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField18.setText("6");
            jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

            jTextField16.setEditable(false);
            jTextField16.setBackground(new java.awt.Color(36, 41, 44));
            jTextField16.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField16.setForeground(new java.awt.Color(255, 255, 255));
            jTextField16.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
            jTextField16.setText(":Fegyver");
            jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

            jTextField17.setEditable(false);
            jTextField17.setBackground(new java.awt.Color(36, 41, 44));
            jTextField17.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
            jTextField17.setForeground(new java.awt.Color(255, 255, 255));
            jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField17.setText("5");
            jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jTextField15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(jTextField18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jTextField17))
                    .addGap(20, 20, 20))
            );

            getContentPane().add(jPanel1);
            jPanel1.setBounds(1040, 10, 150, 130);

            k1.setEditable(false);
            k1.setBackground(new java.awt.Color(0, 0, 0));
            k1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            k1.setForeground(new java.awt.Color(255, 255, 255));
            k1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            k1.setText("●");
            k1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
            getContentPane().add(k1);
            k1.setBounds(220, 380, 50, 50);

            k4.setEditable(false);
            k4.setBackground(new java.awt.Color(0, 0, 0));
            k4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            k4.setForeground(new java.awt.Color(255, 255, 255));
            k4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            k4.setText("●");
            k4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
            getContentPane().add(k4);
            k4.setBounds(220, 280, 50, 50);

            k3.setEditable(false);
            k3.setBackground(new java.awt.Color(0, 0, 0));
            k3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            k3.setForeground(new java.awt.Color(255, 255, 255));
            k3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            k3.setText("●");
            k3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
            getContentPane().add(k3);
            k3.setBounds(220, 430, 50, 50);

            k5.setEditable(false);
            k5.setBackground(new java.awt.Color(0, 0, 0));
            k5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            k5.setForeground(new java.awt.Color(255, 255, 255));
            k5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            k5.setText("●");
            k5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
            getContentPane().add(k5);
            k5.setBounds(220, 480, 50, 50);

            k2.setEditable(false);
            k2.setBackground(new java.awt.Color(0, 0, 0));
            k2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            k2.setForeground(new java.awt.Color(255, 255, 255));
            k2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            k2.setText("●");
            k2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
            getContentPane().add(k2);
            k2.setBounds(220, 330, 50, 50);

            p4.setEditable(false);
            p4.setBackground(new java.awt.Color(0, 0, 0));
            p4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            p4.setForeground(new java.awt.Color(255, 255, 255));
            p4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            p4.setText("●");
            p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
            getContentPane().add(p4);
            p4.setBounds(930, 280, 50, 50);

            p2.setEditable(false);
            p2.setBackground(new java.awt.Color(0, 0, 0));
            p2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            p2.setForeground(new java.awt.Color(255, 255, 255));
            p2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            p2.setText("●");
            p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
            p2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    p2ActionPerformed(evt);
                }
            });
            getContentPane().add(p2);
            p2.setBounds(930, 330, 50, 50);

            p1.setEditable(false);
            p1.setBackground(new java.awt.Color(0, 0, 0));
            p1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            p1.setForeground(new java.awt.Color(255, 255, 255));
            p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            p1.setText("●");
            p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
            p1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    p1ActionPerformed(evt);
                }
            });
            getContentPane().add(p1);
            p1.setBounds(930, 380, 50, 50);

            p3.setEditable(false);
            p3.setBackground(new java.awt.Color(0, 0, 0));
            p3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            p3.setForeground(new java.awt.Color(255, 255, 255));
            p3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            p3.setText("●");
            p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
            getContentPane().add(p3);
            p3.setBounds(930, 430, 50, 50);

            p5.setEditable(false);
            p5.setBackground(new java.awt.Color(0, 0, 0));
            p5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            p5.setForeground(new java.awt.Color(255, 255, 255));
            p5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            p5.setText("●");
            p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
            p5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    p5ActionPerformed(evt);
                }
            });
            getContentPane().add(p5);
            p5.setBounds(930, 480, 50, 50);

            jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 204, 204));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel5.setText("Védekezik");
            getContentPane().add(jLabel5);
            jLabel5.setBounds(940, 250, 100, 22);

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(204, 204, 255));
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel4.setText("Támad");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(160, 250, 100, 22);

            jButton1.setBackground(new java.awt.Color(255, 102, 102));
            jButton1.setForeground(new java.awt.Color(204, 0, 0));
            jButton1.setText("Dob");
            jButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(880, 380, 40, 40);

            jButton2.setBackground(new java.awt.Color(102, 102, 255));
            jButton2.setForeground(new java.awt.Color(0, 51, 204));
            jButton2.setText("Dob");
            jButton2.setMargin(new java.awt.Insets(1, 1, 1, 1));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton2);
            jButton2.setBounds(280, 380, 40, 40);

            jTextField1.setBackground(new java.awt.Color(0, 0, 0));
            jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            jTextField1.setForeground(new java.awt.Color(255, 255, 255));
            jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextField1.setText("A kört nyerte: ");
            getContentPane().add(jTextField1);
            jTextField1.setBounds(340, 360, 520, 80);

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 102, 102));
            getContentPane().add(jLabel6);
            jLabel6.setBounds(1130, 490, 70, 60);

            jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(153, 153, 255));
            getContentPane().add(jLabel7);
            jLabel7.setBounds(30, 490, 70, 60);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/battlemap.png"))); // NOI18N
            getContentPane().add(jLabel1);
            jLabel1.setBounds(0, -140, 1199, 1100);

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (kekjon){
           kekjon=false;
           kmax=0;
           jButton2.setEnabled(false);
           if (tamad){
               for (int i=0;i<jatekosok[0].getFegyver();i++){
                   int dobas=(int)(Math.random()*6+1);
                   kek[i].setText(Integer.toString(dobas));
                   kek[i].setVisible(true);
                   if (dobas>kmax){kmax=dobas;}
               }
               if (kfegy){
                   kmax=kmax+((int)(kmax/jatekosok[0].getModosito()));
               }
               jTextField1.setText(jatekosok[1].getNev()+" következik");
               jLabel7.setText(Integer.toString(kmax));
               jButton1.setEnabled(true);
               jButton2.setEnabled(false);
           }
           else{
               int m; // az életet vagy a pajzsot nézze
               if (jatekosok[0].getPajzs()==0){
                   m=1;
               }
               else {m=jatekosok[0].getPajzs();}
               
              for (int i=0;i<m;i++){
                   int dobas=(int)(Math.random()*6+1);
                   kek[i].setText(Integer.toString(dobas));
                   kek[i].setVisible(true);
                   if (dobas>kmax){kmax=dobas;}
               }
               if (!kfegy){
                   kmax=kmax+((int)(kmax/jatekosok[0].getModosito()));
               }
               jLabel7.setText(Integer.toString(kmax));
               tamad=true;
               levonasK();
               t=new Thread(new Runnable() {
                   @Override
                   public void run() {
                       try {
                           Thread.sleep(5000);
                           jButton2.setEnabled(true);
                           jButton1.setEnabled(false);
                           jLabel4.setText("Támad");
                           jLabel5.setText("Védekezik");
                           Frissit();
                           kekjon=true;
                       } catch (InterruptedException ex) {
                           Logger.getLogger(BattlemapGUI.class.getName()).log(Level.SEVERE, null, ex);
                       }
                       
                   }
               });
               t.start();
               
               // idózite --> frissit();
               
           }
           
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!kekjon){
           jButton1.setEnabled(false);
           pmax=0;
           if (!tamad){
               for (int i=0;i<jatekosok[1].getFegyver();i++){
                   int dobas=(int)(Math.random()*6+1);
                   piros[i].setText(Integer.toString(dobas));
                   piros[i].setVisible(true);
                   if (dobas>pmax){pmax=dobas;}
               }
               if (pfegy){
                   pmax=pmax+((int)(pmax/jatekosok[1].getModosito()));
               }
               jTextField1.setText(jatekosok[0].getNev()+" következik");
               jLabel6.setText(Integer.toString(pmax));
               kekjon=true;
               jButton2.setEnabled(true);
               jButton1.setEnabled(false);
               
           }
           else{
               int m; // az életet vagy a pajzsot nézze
               if (jatekosok[1].getPajzs()==0){
                   m=1;
               }
               else {m=jatekosok[1].getPajzs();}
               
              for (int i=0;i<m;i++){
                   int dobas=(int)(Math.random()*6+1);
                   piros[i].setText(Integer.toString(dobas));
                   piros[i].setVisible(true);
                   if (dobas>pmax){pmax=dobas;}
               }
               if (!pfegy){
                   pmax=pmax+((int)(pmax/jatekosok[1].getModosito()));
               }
               jLabel6.setText(Integer.toString(pmax));
               tamad=false;
               levonasP();
               t=new Thread(new Runnable() {
                   @Override
                   public void run() {
                       try {
                           Thread.sleep(5000);
                           jButton1.setEnabled(true);
                           jButton2.setEnabled(false);
                           jLabel5.setText("Támad");
                           jLabel4.setText("Védekezik");
                       } catch (InterruptedException ex) {
                           Logger.getLogger(BattlemapGUI.class.getName()).log(Level.SEVERE, null, ex);
                       }
                       Frissit();
                        kekjon=false;
                   }
               });
               t.start();
              
               
           }
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattlemapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattlemapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattlemapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattlemapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattlemapGUI().setVisible(true);
            }
        });
    }
    public void Dobokockak(){
        kek[0]=k1;
        kek[1]=k2;
        kek[2]=k3;
        kek[3]=k4;
        kek[4]=k5;
        
        piros[0]=p1;
        piros[1]=p2;
        piros[2]=p3;
        piros[3]=p4;
        piros[4]=p5;
    }
    
    public void Frissit(){
        if (tamad){
            for (int i=kek.length-1;i>=jatekosok[0].getFegyver();i--){
                kek[i].setVisible(false);
            }
            for (int i=0;i<jatekosok[0].getFegyver();i++){
                    kek[i].setVisible(true);
                }
            if (jatekosok[1].getPajzs()!=0){
            for (int i=piros.length-1;i>=jatekosok[1].getPajzs();i--){
                piros[i].setVisible(false);
            }
            for (int i=0;i<jatekosok[1].getPajzs();i++){
                    kek[i].setVisible(true);
                }
            }
            else if (jatekosok[1].getElet()>0){
                for (int i=piros.length-1;i>=1;i--){
                piros[i].setVisible(false);
            }
                for (int i=0;i<jatekosok[1].getElet();i++){
                    kek[i].setVisible(true);
                }
            }
            jTextField1.setText(jatekosok[0].getNev()+" következik");
            if (jatekosok[1].getElet()<=0){
                VisszavonulasKotelezoP();
            }
        }
        else {
            if (jatekosok[0].getPajzs()>0){
                for (int i=kek.length-1;i>=jatekosok[0].getPajzs();i--){
                    kek[i].setVisible(false);
                }
                for (int i=0;i<jatekosok[0].getPajzs();i++){
                    kek[i].setVisible(true);
                }
            }
            else if (jatekosok[0].getElet()>0){
                for (int i=kek.length-1;i>=jatekosok[0].getElet();i--){
                    kek[i].setVisible(false);
                }
                for (int i=0;i<jatekosok[0].getElet();i++){
                    kek[i].setVisible(true);
                }
            }
            for (int i=piros.length-1;i>=jatekosok[1].getFegyver();i--){
                piros[i].setVisible(false);
            }
            for (int i=0;i<jatekosok[1].getFegyver();i++){
                    kek[i].setVisible(true);
                }
            jTextField1.setText(jatekosok[1].getNev()+" következik");
            
            if (jatekosok[0].getElet()<=0){
                VisszavonulasKotelezoK();
            }
        }
        jTextField22.setText(Integer.toString(jatekosok[0].getElet()));
        jTextField24.setText(Integer.toString(jatekosok[0].getPajzs()));
        jTextField25.setText(Integer.toString(jatekosok[0].getFegyver()));
        
        jTextField15.setText(Integer.toString(jatekosok[1].getElet()));
        jTextField18.setText(Integer.toString(jatekosok[1].getPajzs()));
        jTextField17.setText(Integer.toString(jatekosok[1].getFegyver()));
    }
    public void VisszavonulasKotelezoK(){
       jatekosok[0].setHelyzet(-1);
       jatekosok[0].setToltMinden();
       jatekosok[0].setHarcol(false);
       
       t=new Thread(new Runnable() {
           @Override
           public void run() {
               try {
                   jTextField1.setText(jatekosok[0].getNev()+" visszavonul");
                   Thread.sleep(5000);
                   dispose();
               } catch (InterruptedException ex) {
                   Logger.getLogger(BattlemapGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
           }});
       t.start();
  
    }
    public void VisszavonulasKotelezoP(){
       jatekosok[1].setHelyzet(133);
       jatekosok[1].setToltMinden();
       jatekosok[1].setHarcol(false);
       
       t=new Thread(new Runnable() {
           @Override
           public void run() {
               try {
                   jTextField1.setText(jatekosok[1].getNev()+" visszavonul");
                   Thread.sleep(5000);
                   dispose();
               } catch (InterruptedException ex) {
                   Logger.getLogger(BattlemapGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
           }});
       t.start();
    }
    public void levonasP(){
        if (kmax>pmax){jTextField1.setText(jatekosok[0].getNev()+" nyert!");
            if (jatekosok[1].getPajzs()>0){jatekosok[1].setVeszitPajzs();}
            else if (jatekosok[1].getElet()>1){jatekosok[1].setVeszitElet();}
            else{VisszavonulasKotelezoP();}}
        else if (pmax>kmax){jTextField1.setText(jatekosok[1].getNev()+" nyert!");
            if (jatekosok[0].getFegyver()>1){jatekosok[0].setVeszitFegyver();}
            else{VisszavonulasKotelezoK();}}
        else {jTextField1.setText("Döntetlen!");}
    }
    public void levonasK(){
        if (kmax<pmax){jTextField1.setText(jatekosok[1].getNev()+" nyert!");
            if (jatekosok[0].getPajzs()>0){jatekosok[0].setVeszitPajzs();}
            else if (jatekosok[0].getElet()>1){jatekosok[0].setVeszitElet();}
            else{VisszavonulasKotelezoK();}}
        else if (pmax<kmax){jTextField1.setText(jatekosok[0].getNev()+" nyert!");
            if (jatekosok[1].getFegyver()>1){jatekosok[1].setVeszitFegyver();}
            else{VisszavonulasKotelezoP();}}
        else {jTextField1.setText("Döntetlen!");}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField k1;
    private javax.swing.JTextField k2;
    private javax.swing.JTextField k3;
    private javax.swing.JTextField k4;
    private javax.swing.JTextField k5;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    // End of variables declaration//GEN-END:variables

    void addActionListener(WindowListener windowListener) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
