
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileSystemView;

public class KilepoGUI extends javax.swing.JFrame {

    Jatekos jatekosok[];
    TablaGUI t;
    int kor;
    public KilepoGUI() {
        initComponents();
    }
    
    public KilepoGUI(Jatekos jatekosok[], TablaGUI t,int kor) {
        this.t=t;
        this.jatekosok=jatekosok;
        this.kor=kor;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/kepek/ikon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1063, 576));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mentés nélküli adatok elvesznek. Kérjük válasszon az alábbi lehetőségekből:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 460, 460, 20);

        jButton1.setBackground(new java.awt.Color(36, 41, 44));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mégsem");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 41, 44)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(305, 500, 130, 30);

        jButton2.setBackground(new java.awt.Color(36, 41, 44));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mentés és kilépés");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 41, 44)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 500, 130, 30);

        jButton3.setBackground(new java.awt.Color(36, 41, 44));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Kilépés mentés nélkül");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 41, 44)));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 500, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kilepo.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1063, 576);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            BufferedWriter bw=new BufferedWriter(new FileWriter(new File("mentes.txt")));
            
            bw.write(jatekosok[0].getNev()+"\t"+jatekosok[1].getNev()+"\n");
            bw.write(jatekosok[0].getElet()+"\t"+jatekosok[1].getElet()+"\n");
            bw.write(jatekosok[0].getPajzs()+"\t"+jatekosok[1].getPajzs()+"\n");
            bw.write(jatekosok[0].getFegyver()+"\t"+jatekosok[1].getFegyver()+"\n");
            bw.write(jatekosok[0].getModosito()+"\t"+jatekosok[1].getModosito()+"\n");
            bw.write(jatekosok[0].getHelyzet()+"\t"+jatekosok[1].getHelyzet()+"\n");
            bw.write(jatekosok[0].getHanykorbol()+"\t"+jatekosok[1].getHanykorbol()+"\n");
            bw.write(jatekosok[0].getKarakter()+"\t"+jatekosok[1].getKarakter()+"\n");
            bw.write(jatekosok[0].getHarcol()+"\t"+jatekosok[1].getHarcol()+"\n");
            bw.write(jatekosok[0].getKikerul()+"\t"+jatekosok[1].getKikerul()+"\n");
            bw.write(kor+"\n");
            bw.close();
            
            System.exit(0);
    }
        catch(Exception e){
                e.printStackTrace();
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KilepoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KilepoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KilepoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KilepoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KilepoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
