
import javax.swing.AbstractButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TeszTa
 */
public class BoltGUI extends javax.swing.JFrame {

    int fizetendo=0;
    Boolean bicikli=false,benzines=false,elektromos=false,haz=false, okohaz=false, eszkozok=false, furdo=false, butor=false;
    GUI g;
    public BoltGUI() {
        
        initComponents();
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        
        jToggleButton7.setEnabled(false);
            jToggleButton6.setEnabled(false);
        
        jToggleButton8.setEnabled(false);
            jToggleButton9.setEnabled(false);
            jToggleButton10.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
            
       
    }
    
    public BoltGUI(GUI f) {
        g=f;
        initComponents();
        g.setEnabled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        
        jToggleButton7.setEnabled(false);
            jToggleButton6.setEnabled(false);
        
        jToggleButton8.setEnabled(false);
            jToggleButton9.setEnabled(false);
            jToggleButton10.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
            setLocationRelativeTo(null);
            if (g.jatekosok.get(g.aktualisjatekos).getBicikli()){jToggleButton5.setEnabled(false);}
            if (g.jatekosok.get(g.aktualisjatekos).getAuto() && !g.jatekosok.get(g.aktualisjatekos).getElektromos()){jToggleButton3.setEnabled(false);jToggleButton4.setEnabled(true);jToggleButton4.setText("<html>Elektromos<br>+5.000.000 Ft</html>");}
            else if (g.jatekosok.get(g.aktualisjatekos).getElektromos()){jToggleButton1.setEnabled(false);}
            if (g.jatekosok.get(g.aktualisjatekos).getHaz().getVane() && !g.jatekosok.get(g.aktualisjatekos).getHaz().getNapelem()){jToggleButton6.setEnabled(false);jToggleButton7.setEnabled(true);jToggleButton7.setText("<html>Napelemek<br>+5.000.000 Ft</html>");jToggleButton8.setEnabled(true);jToggleButton10.setEnabled(true);jToggleButton9.setEnabled(true);}
            else if (g.jatekosok.get(g.aktualisjatekos).getHaz().getNapelem()){jToggleButton6.setEnabled(false);jToggleButton7.setEnabled(false);jToggleButton8.setEnabled(true);jToggleButton10.setEnabled(true);jToggleButton9.setEnabled(true);}
            if (g.jatekosok.get(g.aktualisjatekos).getHaz().getHuto()){jToggleButton8.setEnabled(false);}
            if (g.jatekosok.get(g.aktualisjatekos).getHaz().getFurdoszoba()){jToggleButton10.setEnabled(false);}
            if (g.jatekosok.get(g.aktualisjatekos).getHaz().getButorok()){jToggleButton9.setEnabled(false);}
            if (g.jatekosok.get(g.aktualisjatekos).getHaz().getNapelem() && g.jatekosok.get(g.aktualisjatekos).getHaz().getHuto() && g.jatekosok.get(g.aktualisjatekos).getHaz().getFurdoszoba() && g.jatekosok.get(g.aktualisjatekos).getHaz().getButorok()){jToggleButton2.setEnabled(false); jLabel6.setText("Te már mindent megvettél");jButton1.setEnabled(false);}
            
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(853, 476));
        setMinimumSize(new java.awt.Dimension(853, 476));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(240, 240, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Összeg: ");

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton1.setText("Autó");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton2.setText("Ház");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Vásárlás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kilépés");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("<html>Benzines<br>5.000.000 Ft</html>");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("<html>Elektromos<br>10.000.000 Ft</html>");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton5.setText("Bicikli");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("<html>Hagyományos<br>15.000.000 Ft</html>");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("<html>Ökoház<br>20.000.000 Ft</html>");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("Háztartási eszközök");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.setText("Bútorok");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.setText("Fürdőszoba");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("10.000 Ft");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("150.000 Ft");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("200.000 Ft");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("500.000 Ft");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText(" ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Bicikli: +30 Ökopont\nElektromos autó: +50 Ökopont\nÖkoház/Napelem: +60 Ökopont");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jToggleButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jToggleButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jToggleButton8, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jToggleButton3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jToggleButton4))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jToggleButton6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jToggleButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jToggleButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected() ){
            if (!g.jatekosok.get(g.aktualisjatekos).getAuto()){
            jToggleButton3.setEnabled(true);
            jToggleButton3.setSelected(true);
            jToggleButton4.setEnabled(true);
            jToggleButton4.setSelected(false);
            if (!elektromos && !benzines){
                benzines=true;
                fizetendo+=5000000;
            }}
            else {
                jToggleButton4.setSelected(true);
                elektromos=true;
                fizetendo+=5000000;
            }
        }
        else if (g.jatekosok.get(g.aktualisjatekos).getAuto()){
            jToggleButton4.setSelected(false);
            elektromos=false;
            fizetendo-=5000000;
        }
        else {
            jToggleButton3.setEnabled(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setEnabled(false);
            jToggleButton4.setSelected(false);
            if (benzines){
                benzines=false;
                fizetendo-=5000000;
            }
            else if (elektromos){
                elektromos=false;
                fizetendo-=10000000;
            }
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
       if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jLabel2.setEnabled(true);
            if (!bicikli){
            fizetendo+=10000;
            bicikli=true;
            }
        }
        else {
            jLabel2.setEnabled(false);
            if (bicikli){
                fizetendo-=10000;
                bicikli=false;
            }
            
        }
       jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jToggleButton4.setSelected(false);
            if (elektromos){fizetendo-=5000000;elektromos=false;benzines=true;}
        }
        else {
            jToggleButton3.setSelected(true);
            
        }
         jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jToggleButton3.setSelected(false);
            fizetendo+=5000000;
            elektromos=true;
            benzines=false;
            if (g.jatekosok.get(g.aktualisjatekos).getAuto()){
                jToggleButton1.setSelected(true);
                
            }
        }
       else if(g.jatekosok.get(g.aktualisjatekos).getAuto()){
           jToggleButton1.setSelected(false);
           elektromos=false;
           fizetendo-=5000000;
       }
        else {
            jToggleButton4.setSelected(true);
            
        }
       jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            if(g.jatekosok.get(g.aktualisjatekos).getHaz().getVane()){
                jToggleButton6.setEnabled(false);
                if(g.jatekosok.get(g.aktualisjatekos).getHaz().getNapelem()){
                    jToggleButton7.setEnabled(false);
                }
                jToggleButton7.setSelected(true);
                okohaz=true;
                fizetendo+=5000000;
            }
            else{
            jToggleButton6.setEnabled(true);
            jToggleButton6.setSelected(true);
            jToggleButton7.setEnabled(true);
            jToggleButton7.setSelected(false);
            jToggleButton8.setEnabled(true);
            jToggleButton9.setEnabled(true);
            jToggleButton10.setEnabled(true);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
            if(!haz && !okohaz){fizetendo+=15000000;haz=true;}}
        }
        else {
            if ((g.jatekosok.get(g.aktualisjatekos).getHaz().getVane())){
                if (okohaz){
                fizetendo-=5000000;
                }
                jToggleButton7.setSelected(false);
                okohaz=false;
                
            }
            else{
            jToggleButton6.setEnabled(false);
            jToggleButton6.setSelected(false);
            jToggleButton7.setEnabled(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setEnabled(false);
            jToggleButton9.setEnabled(false);
            jToggleButton10.setEnabled(false);
            if (haz){
                fizetendo-=15000000;
                haz=false;
            }
            else if (okohaz){
                fizetendo-=20000000;
                okohaz=false;
            }
            if (eszkozok){eszkozok=false;fizetendo-=150000;}
            if (furdo){furdo=false; fizetendo-=200000;}
            if (butor){butor=false; fizetendo-=500000;}
            
            }
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jToggleButton7.setSelected(false);
            if(elektromos || !haz){
                elektromos=false;
                haz=true;
                fizetendo-=5000000;
            }
           
        }
        else {
            jToggleButton6.setSelected(true);
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jToggleButton6.setSelected(false);
            if(haz ){
                haz=false;
                fizetendo+=5000000;
                okohaz=true;
                
            }
            else if(g.jatekosok.get(g.aktualisjatekos).getHaz().getVane()){
                haz=false;
                fizetendo+=5000000;
                okohaz=true;
                jToggleButton2.setSelected(true);
            }
        }
        else {
            if (g.jatekosok.get(g.aktualisjatekos).getHaz().getVane()){
                jToggleButton2.setSelected(false);
                okohaz=false;
                fizetendo-=5000000;
            }
            else {
            jToggleButton7.setSelected(true);
            }
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jLabel3.setEnabled(true);
            eszkozok=true;
            fizetendo+=150000;
        }
        else {
            jLabel3.setEnabled(false);
            eszkozok=false;
            fizetendo-=150000;
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
         
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jLabel4.setEnabled(true);
            furdo=true;
            fizetendo+=200000;
        }
        else {
            jLabel4.setEnabled(false);
            furdo=false;
            fizetendo-=200000;
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        if (((AbstractButton)evt.getSource()).getModel().isSelected()){
            jLabel5.setEnabled(true);
            butor=true;
            fizetendo+=500000;
        }
        else {
            jLabel5.setEnabled(false);
            butor=false;
            fizetendo-=500000;
            
        }
        jLabel1.setText("Összeg: "+kiir(fizetendo)+" Ft");
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        g.setEnabled(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(g.jatekosok.get(g.aktualisjatekos).getPenz()<fizetendo){
           jLabel6.setText("Sajnálom, de ennyi pénzed nincs");
        }
        else if (fizetendo>0){
            g.jatekosok.get(g.aktualisjatekos).addPenz((-1)*fizetendo);
            if (bicikli){g.jatekosok.get(g.aktualisjatekos).setBicikli(true);g.jatekosok.get(g.aktualisjatekos).addPont(30);}
            if (benzines && !g.jatekosok.get(g.aktualisjatekos).getAuto()){g.jatekosok.get(g.aktualisjatekos).setAuto(true);}
            else if (elektromos){g.jatekosok.get(g.aktualisjatekos).setAuto(true); g.jatekosok.get(g.aktualisjatekos).setElektromos(true);g.jatekosok.get(g.aktualisjatekos).addPont(50);}
            if (haz && !g.jatekosok.get(g.aktualisjatekos).getHaz().getVane()){g.jatekosok.get(g.aktualisjatekos).getHaz().setVane(true);}
            else if (okohaz){g.jatekosok.get(g.aktualisjatekos).getHaz().setVane(true); g.jatekosok.get(g.aktualisjatekos).getHaz().setNapelem(true);g.jatekosok.get(g.aktualisjatekos).addPont(60);}
            if (eszkozok){g.jatekosok.get(g.aktualisjatekos).getHaz().setHuto(true);g.jatekosok.get(g.aktualisjatekos).getHaz().setMikro(true);g.jatekosok.get(g.aktualisjatekos).getHaz().setMosogato(true);g.jatekosok.get(g.aktualisjatekos).getHaz().setMosogatogep(true);g.jatekosok.get(g.aktualisjatekos).getHaz().setMosogep(true);}
            if (furdo){g.jatekosok.get(g.aktualisjatekos).getHaz().setFurdoszoba(true);g.jatekosok.get(g.aktualisjatekos).getHaz().setZuhanyzo(true);}
            if (butor){g.jatekosok.get(g.aktualisjatekos).getHaz().setButorok(true);g.jatekosok.get(g.aktualisjatekos).getHaz().setFabutor(true);}
            g.jatekosok.get(g.aktualisjatekos).getHaz().setTeljes();
            g.jatekosok.get(g.aktualisjatekos).getHaz().setKimaxolva();
           
            g.setTextJLabel("Vásárolt");
            
            
            new GUI(g).setVisible(true);
            g.dispose();
            dispose();
        }
        else{
            jButton2.doClick();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public String kiir(int sz){
        int szamlalo=0;
        String s=Integer.toString(sz);
        String k="";
        for (int i=s.length()-1;i>=0;i--){
           if (szamlalo==3){
                k="."+k;
                szamlalo=0;
            }
        
            k=s.substring(i,i+1)+k;
            szamlalo++;
        }
        return k;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoltGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
